/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CirclStarlinkInstallationsRouteImport } from './routes/circl-starlink-installations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomerHelpRouteImport } from './routes/customer-help'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as EventLinkRouteImport } from './routes/event-link'
import { Route as InstallTermsAndConditionsRouteImport } from './routes/install-terms-and-conditions'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PropertyNetworksRouteImport } from './routes/property-networks'
import { Route as PropertyPlannerRouteImport } from './routes/property-planner'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as StarlinkRouteImport } from './routes/starlink'
import { Route as StarlinkOfferRouteImport } from './routes/starlink-offer'
import { Route as VingearRouteImport } from './routes/vingear'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as AboutBusinessInformationRouteImport } from './routes/about.business-information'
import { Route as AboutCapabilityRouteImport } from './routes/about.capability'
import { Route as AboutHowWeWorkRouteImport } from './routes/about.how-we-work'
import { Route as AboutSafetyAndCredentialsRouteImport } from './routes/about.safety-and-credentials'
import { Route as AboutSupportRouteImport } from './routes/about.support'
import { Route as CirclStarlinkInstallationsIndexRouteImport } from './routes/circl-starlink-installations.index'
import { Route as CirclStarlinkInstallationsSlugRouteImport } from './routes/circl-starlink-installations.$slug'
import { Route as CustomerHelpIndexRouteImport } from './routes/customer-help.index'
import { Route as CustomerHelpSlugRouteImport } from './routes/customer-help.$slug'
import { Route as EventLinkIndexRouteImport } from './routes/event-link.index'
import { Route as EventLinkSlugRouteImport } from './routes/event-link.$slug'
import { Route as EventLinkOrganisersRouteImport } from './routes/event-link.organisers'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as PropertyNetworksIndexRouteImport } from './routes/property-networks.index'
import { Route as PropertyNetworksSlugRouteImport } from './routes/property-networks.$slug'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as RuralConnectionsIndexRouteImport } from './routes/rural-connections.index'
import { Route as RuralConnectionsSlugRouteImport } from './routes/rural-connections.$slug'
import { Route as SecurityIndexRouteImport } from './routes/security.index'
import { Route as SecuritySlugRouteImport } from './routes/security.$slug'
import { Route as ServiceAreasIndexRouteImport } from './routes/service-areas.index'
import { Route as ServiceAreasSlugRouteImport } from './routes/service-areas.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'
import { Route as StarlinkIndexRouteImport } from './routes/starlink.index'
import { Route as StarlinkSlugRouteImport } from './routes/starlink.$slug'
import { Route as VingearIndexRouteImport } from './routes/vingear.index'
import { Route as VingearSlugRouteImport } from './routes/vingear.$slug'
import { Route as ResourcesDownloadsIndexRouteImport } from './routes/resources.downloads.index'
import { Route as ResourcesDownloadsSlugRouteImport } from './routes/resources.downloads.$slug'
import { Route as SecurityPackagesSlugRouteImport } from './routes/security.packages.$slug'
import { Route as ServiceAreasRegionSlugRouteImport } from './routes/service-areas.region.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclStarlinkInstallationsRoute =
  CirclStarlinkInstallationsRouteImport.update({
    id: '/circl-starlink-installations',
    path: '/circl-starlink-installations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerHelpRoute = CustomerHelpRouteImport.update({
  id: '/customer-help',
  path: '/customer-help',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const EventLinkRoute = EventLinkRouteImport.update({
  id: '/event-link',
  path: '/event-link',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallTermsAndConditionsRoute =
  InstallTermsAndConditionsRouteImport.update({
    id: '/install-terms-and-conditions',
    path: '/install-terms-and-conditions',
    getParentRoute: () => rootRouteImport,
  } as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyNetworksRoute = PropertyNetworksRouteImport.update({
  id: '/property-networks',
  path: '/property-networks',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyPlannerRoute = PropertyPlannerRouteImport.update({
  id: '/property-planner',
  path: '/property-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const StarlinkRoute = StarlinkRouteImport.update({
  id: '/starlink',
  path: '/starlink',
  getParentRoute: () => rootRouteImport,
} as any)
const StarlinkOfferRoute = StarlinkOfferRouteImport.update({
  id: '/starlink-offer',
  path: '/starlink-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const VingearRoute = VingearRouteImport.update({
  id: '/vingear',
  path: '/vingear',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const AboutBusinessInformationRoute =
  AboutBusinessInformationRouteImport.update({
    id: '/business-information',
    path: '/business-information',
    getParentRoute: () => AboutRoute,
  } as any)
const AboutCapabilityRoute = AboutCapabilityRouteImport.update({
  id: '/capability',
  path: '/capability',
  getParentRoute: () => AboutRoute,
} as any)
const AboutHowWeWorkRoute = AboutHowWeWorkRouteImport.update({
  id: '/how-we-work',
  path: '/how-we-work',
  getParentRoute: () => AboutRoute,
} as any)
const AboutSafetyAndCredentialsRoute =
  AboutSafetyAndCredentialsRouteImport.update({
    id: '/safety-and-credentials',
    path: '/safety-and-credentials',
    getParentRoute: () => AboutRoute,
  } as any)
const AboutSupportRoute = AboutSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AboutRoute,
} as any)
const CirclStarlinkInstallationsIndexRoute =
  CirclStarlinkInstallationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CirclStarlinkInstallationsRoute,
  } as any)
const CirclStarlinkInstallationsSlugRoute =
  CirclStarlinkInstallationsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => CirclStarlinkInstallationsRoute,
  } as any)
const CustomerHelpIndexRoute = CustomerHelpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerHelpRoute,
} as any)
const CustomerHelpSlugRoute = CustomerHelpSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CustomerHelpRoute,
} as any)
const EventLinkIndexRoute = EventLinkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventLinkRoute,
} as any)
const EventLinkSlugRoute = EventLinkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventLinkRoute,
} as any)
const EventLinkOrganisersRoute = EventLinkOrganisersRouteImport.update({
  id: '/organisers',
  path: '/organisers',
  getParentRoute: () => EventLinkRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JournalRoute,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyNetworksIndexRoute = PropertyNetworksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropertyNetworksRoute,
} as any)
const PropertyNetworksSlugRoute = PropertyNetworksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PropertyNetworksRoute,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RuralConnectionsIndexRoute = RuralConnectionsIndexRouteImport.update({
  id: '/rural-connections/',
  path: '/rural-connections/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuralConnectionsSlugRoute = RuralConnectionsSlugRouteImport.update({
  id: '/rural-connections/$slug',
  path: '/rural-connections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityIndexRoute = SecurityIndexRouteImport.update({
  id: '/security/',
  path: '/security/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecuritySlugRoute = SecuritySlugRouteImport.update({
  id: '/security/$slug',
  path: '/security/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasIndexRoute = ServiceAreasIndexRouteImport.update({
  id: '/service-areas/',
  path: '/service-areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasSlugRoute = ServiceAreasSlugRouteImport.update({
  id: '/service-areas/$slug',
  path: '/service-areas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SolutionsRoute,
} as any)
const StarlinkIndexRoute = StarlinkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StarlinkRoute,
} as any)
const StarlinkSlugRoute = StarlinkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StarlinkRoute,
} as any)
const VingearIndexRoute = VingearIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VingearRoute,
} as any)
const VingearSlugRoute = VingearSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VingearRoute,
} as any)
const ResourcesDownloadsIndexRoute = ResourcesDownloadsIndexRouteImport.update({
  id: '/resources/downloads/',
  path: '/resources/downloads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesDownloadsSlugRoute = ResourcesDownloadsSlugRouteImport.update({
  id: '/resources/downloads/$slug',
  path: '/resources/downloads/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityPackagesSlugRoute = SecurityPackagesSlugRouteImport.update({
  id: '/security/packages/$slug',
  path: '/security/packages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRegionSlugRoute = ServiceAreasRegionSlugRouteImport.update({
  id: '/service-areas/region/$slug',
  path: '/service-areas/region/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/circl-starlink-installations': typeof CirclStarlinkInstallationsRouteWithChildren
  '/contact': typeof ContactRoute
  '/customer-help': typeof CustomerHelpRouteWithChildren
  '/estimate': typeof EstimateRoute
  '/event-link': typeof EventLinkRouteWithChildren
  '/install-terms-and-conditions': typeof InstallTermsAndConditionsRoute
  '/journal': typeof JournalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/property-networks': typeof PropertyNetworksRouteWithChildren
  '/property-planner': typeof PropertyPlannerRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/starlink': typeof StarlinkRouteWithChildren
  '/starlink-offer': typeof StarlinkOfferRoute
  '/vingear': typeof VingearRouteWithChildren
  '/about/business-information': typeof AboutBusinessInformationRoute
  '/about/capability': typeof AboutCapabilityRoute
  '/about/how-we-work': typeof AboutHowWeWorkRoute
  '/about/safety-and-credentials': typeof AboutSafetyAndCredentialsRoute
  '/about/support': typeof AboutSupportRoute
  '/circl-starlink-installations/$slug': typeof CirclStarlinkInstallationsSlugRoute
  '/customer-help/$slug': typeof CustomerHelpSlugRoute
  '/event-link/$slug': typeof EventLinkSlugRoute
  '/event-link/organisers': typeof EventLinkOrganisersRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/property-networks/$slug': typeof PropertyNetworksSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/rural-connections/$slug': typeof RuralConnectionsSlugRoute
  '/security/$slug': typeof SecuritySlugRoute
  '/service-areas/$slug': typeof ServiceAreasSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/starlink/$slug': typeof StarlinkSlugRoute
  '/vingear/$slug': typeof VingearSlugRoute
  '/about/': typeof AboutIndexRoute
  '/circl-starlink-installations/': typeof CirclStarlinkInstallationsIndexRoute
  '/customer-help/': typeof CustomerHelpIndexRoute
  '/event-link/': typeof EventLinkIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/property-networks/': typeof PropertyNetworksIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/rural-connections/': typeof RuralConnectionsIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/starlink/': typeof StarlinkIndexRoute
  '/vingear/': typeof VingearIndexRoute
  '/resources/downloads/$slug': typeof ResourcesDownloadsSlugRoute
  '/security/packages/$slug': typeof SecurityPackagesSlugRoute
  '/service-areas/region/$slug': typeof ServiceAreasRegionSlugRoute
  '/resources/downloads/': typeof ResourcesDownloadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/estimate': typeof EstimateRoute
  '/install-terms-and-conditions': typeof InstallTermsAndConditionsRoute
  '/privacy': typeof PrivacyRoute
  '/property-planner': typeof PropertyPlannerRoute
  '/starlink-offer': typeof StarlinkOfferRoute
  '/about/business-information': typeof AboutBusinessInformationRoute
  '/about/capability': typeof AboutCapabilityRoute
  '/about/how-we-work': typeof AboutHowWeWorkRoute
  '/about/safety-and-credentials': typeof AboutSafetyAndCredentialsRoute
  '/about/support': typeof AboutSupportRoute
  '/circl-starlink-installations/$slug': typeof CirclStarlinkInstallationsSlugRoute
  '/customer-help/$slug': typeof CustomerHelpSlugRoute
  '/event-link/$slug': typeof EventLinkSlugRoute
  '/event-link/organisers': typeof EventLinkOrganisersRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/property-networks/$slug': typeof PropertyNetworksSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/rural-connections/$slug': typeof RuralConnectionsSlugRoute
  '/security/$slug': typeof SecuritySlugRoute
  '/service-areas/$slug': typeof ServiceAreasSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/starlink/$slug': typeof StarlinkSlugRoute
  '/vingear/$slug': typeof VingearSlugRoute
  '/about': typeof AboutIndexRoute
  '/circl-starlink-installations': typeof CirclStarlinkInstallationsIndexRoute
  '/customer-help': typeof CustomerHelpIndexRoute
  '/event-link': typeof EventLinkIndexRoute
  '/journal': typeof JournalIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/property-networks': typeof PropertyNetworksIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/rural-connections': typeof RuralConnectionsIndexRoute
  '/security': typeof SecurityIndexRoute
  '/service-areas': typeof ServiceAreasIndexRoute
  '/services': typeof ServicesIndexRoute
  '/solutions': typeof SolutionsIndexRoute
  '/starlink': typeof StarlinkIndexRoute
  '/vingear': typeof VingearIndexRoute
  '/resources/downloads/$slug': typeof ResourcesDownloadsSlugRoute
  '/security/packages/$slug': typeof SecurityPackagesSlugRoute
  '/service-areas/region/$slug': typeof ServiceAreasRegionSlugRoute
  '/resources/downloads': typeof ResourcesDownloadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/circl-starlink-installations': typeof CirclStarlinkInstallationsRouteWithChildren
  '/contact': typeof ContactRoute
  '/customer-help': typeof CustomerHelpRouteWithChildren
  '/estimate': typeof EstimateRoute
  '/event-link': typeof EventLinkRouteWithChildren
  '/install-terms-and-conditions': typeof InstallTermsAndConditionsRoute
  '/journal': typeof JournalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/property-networks': typeof PropertyNetworksRouteWithChildren
  '/property-planner': typeof PropertyPlannerRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/starlink': typeof StarlinkRouteWithChildren
  '/starlink-offer': typeof StarlinkOfferRoute
  '/vingear': typeof VingearRouteWithChildren
  '/about/business-information': typeof AboutBusinessInformationRoute
  '/about/capability': typeof AboutCapabilityRoute
  '/about/how-we-work': typeof AboutHowWeWorkRoute
  '/about/safety-and-credentials': typeof AboutSafetyAndCredentialsRoute
  '/about/support': typeof AboutSupportRoute
  '/circl-starlink-installations/$slug': typeof CirclStarlinkInstallationsSlugRoute
  '/customer-help/$slug': typeof CustomerHelpSlugRoute
  '/event-link/$slug': typeof EventLinkSlugRoute
  '/event-link/organisers': typeof EventLinkOrganisersRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/property-networks/$slug': typeof PropertyNetworksSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/rural-connections/$slug': typeof RuralConnectionsSlugRoute
  '/security/$slug': typeof SecuritySlugRoute
  '/service-areas/$slug': typeof ServiceAreasSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/starlink/$slug': typeof StarlinkSlugRoute
  '/vingear/$slug': typeof VingearSlugRoute
  '/about/': typeof AboutIndexRoute
  '/circl-starlink-installations/': typeof CirclStarlinkInstallationsIndexRoute
  '/customer-help/': typeof CustomerHelpIndexRoute
  '/event-link/': typeof EventLinkIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/property-networks/': typeof PropertyNetworksIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/rural-connections/': typeof RuralConnectionsIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/starlink/': typeof StarlinkIndexRoute
  '/vingear/': typeof VingearIndexRoute
  '/resources/downloads/$slug': typeof ResourcesDownloadsSlugRoute
  '/security/packages/$slug': typeof SecurityPackagesSlugRoute
  '/service-areas/region/$slug': typeof ServiceAreasRegionSlugRoute
  '/resources/downloads/': typeof ResourcesDownloadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/circl-starlink-installations'
    | '/contact'
    | '/customer-help'
    | '/estimate'
    | '/event-link'
    | '/install-terms-and-conditions'
    | '/journal'
    | '/privacy'
    | '/property-networks'
    | '/property-planner'
    | '/solutions'
    | '/starlink'
    | '/starlink-offer'
    | '/vingear'
    | '/about/business-information'
    | '/about/capability'
    | '/about/how-we-work'
    | '/about/safety-and-credentials'
    | '/about/support'
    | '/circl-starlink-installations/$slug'
    | '/customer-help/$slug'
    | '/event-link/$slug'
    | '/event-link/organisers'
    | '/journal/$slug'
    | '/projects/$slug'
    | '/property-networks/$slug'
    | '/resources/$slug'
    | '/rural-connections/$slug'
    | '/security/$slug'
    | '/service-areas/$slug'
    | '/services/$slug'
    | '/solutions/$slug'
    | '/starlink/$slug'
    | '/vingear/$slug'
    | '/about/'
    | '/circl-starlink-installations/'
    | '/customer-help/'
    | '/event-link/'
    | '/journal/'
    | '/projects/'
    | '/property-networks/'
    | '/resources/'
    | '/rural-connections/'
    | '/security/'
    | '/service-areas/'
    | '/services/'
    | '/solutions/'
    | '/starlink/'
    | '/vingear/'
    | '/resources/downloads/$slug'
    | '/security/packages/$slug'
    | '/service-areas/region/$slug'
    | '/resources/downloads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/estimate'
    | '/install-terms-and-conditions'
    | '/privacy'
    | '/property-planner'
    | '/starlink-offer'
    | '/about/business-information'
    | '/about/capability'
    | '/about/how-we-work'
    | '/about/safety-and-credentials'
    | '/about/support'
    | '/circl-starlink-installations/$slug'
    | '/customer-help/$slug'
    | '/event-link/$slug'
    | '/event-link/organisers'
    | '/journal/$slug'
    | '/projects/$slug'
    | '/property-networks/$slug'
    | '/resources/$slug'
    | '/rural-connections/$slug'
    | '/security/$slug'
    | '/service-areas/$slug'
    | '/services/$slug'
    | '/solutions/$slug'
    | '/starlink/$slug'
    | '/vingear/$slug'
    | '/about'
    | '/circl-starlink-installations'
    | '/customer-help'
    | '/event-link'
    | '/journal'
    | '/projects'
    | '/property-networks'
    | '/resources'
    | '/rural-connections'
    | '/security'
    | '/service-areas'
    | '/services'
    | '/solutions'
    | '/starlink'
    | '/vingear'
    | '/resources/downloads/$slug'
    | '/security/packages/$slug'
    | '/service-areas/region/$slug'
    | '/resources/downloads'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/circl-starlink-installations'
    | '/contact'
    | '/customer-help'
    | '/estimate'
    | '/event-link'
    | '/install-terms-and-conditions'
    | '/journal'
    | '/privacy'
    | '/property-networks'
    | '/property-planner'
    | '/solutions'
    | '/starlink'
    | '/starlink-offer'
    | '/vingear'
    | '/about/business-information'
    | '/about/capability'
    | '/about/how-we-work'
    | '/about/safety-and-credentials'
    | '/about/support'
    | '/circl-starlink-installations/$slug'
    | '/customer-help/$slug'
    | '/event-link/$slug'
    | '/event-link/organisers'
    | '/journal/$slug'
    | '/projects/$slug'
    | '/property-networks/$slug'
    | '/resources/$slug'
    | '/rural-connections/$slug'
    | '/security/$slug'
    | '/service-areas/$slug'
    | '/services/$slug'
    | '/solutions/$slug'
    | '/starlink/$slug'
    | '/vingear/$slug'
    | '/about/'
    | '/circl-starlink-installations/'
    | '/customer-help/'
    | '/event-link/'
    | '/journal/'
    | '/projects/'
    | '/property-networks/'
    | '/resources/'
    | '/rural-connections/'
    | '/security/'
    | '/service-areas/'
    | '/services/'
    | '/solutions/'
    | '/starlink/'
    | '/vingear/'
    | '/resources/downloads/$slug'
    | '/security/packages/$slug'
    | '/service-areas/region/$slug'
    | '/resources/downloads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  CirclStarlinkInstallationsRoute: typeof CirclStarlinkInstallationsRouteWithChildren
  ContactRoute: typeof ContactRoute
  CustomerHelpRoute: typeof CustomerHelpRouteWithChildren
  EstimateRoute: typeof EstimateRoute
  EventLinkRoute: typeof EventLinkRouteWithChildren
  InstallTermsAndConditionsRoute: typeof InstallTermsAndConditionsRoute
  JournalRoute: typeof JournalRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  PropertyNetworksRoute: typeof PropertyNetworksRouteWithChildren
  PropertyPlannerRoute: typeof PropertyPlannerRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  StarlinkRoute: typeof StarlinkRouteWithChildren
  StarlinkOfferRoute: typeof StarlinkOfferRoute
  VingearRoute: typeof VingearRouteWithChildren
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  RuralConnectionsSlugRoute: typeof RuralConnectionsSlugRoute
  SecuritySlugRoute: typeof SecuritySlugRoute
  ServiceAreasSlugRoute: typeof ServiceAreasSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  RuralConnectionsIndexRoute: typeof RuralConnectionsIndexRoute
  SecurityIndexRoute: typeof SecurityIndexRoute
  ServiceAreasIndexRoute: typeof ServiceAreasIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ResourcesDownloadsSlugRoute: typeof ResourcesDownloadsSlugRoute
  SecurityPackagesSlugRoute: typeof SecurityPackagesSlugRoute
  ServiceAreasRegionSlugRoute: typeof ServiceAreasRegionSlugRoute
  ResourcesDownloadsIndexRoute: typeof ResourcesDownloadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circl-starlink-installations': {
      id: '/circl-starlink-installations'
      path: '/circl-starlink-installations'
      fullPath: '/circl-starlink-installations'
      preLoaderRoute: typeof CirclStarlinkInstallationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-help': {
      id: '/customer-help'
      path: '/customer-help'
      fullPath: '/customer-help'
      preLoaderRoute: typeof CustomerHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-link': {
      id: '/event-link'
      path: '/event-link'
      fullPath: '/event-link'
      preLoaderRoute: typeof EventLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install-terms-and-conditions': {
      id: '/install-terms-and-conditions'
      path: '/install-terms-and-conditions'
      fullPath: '/install-terms-and-conditions'
      preLoaderRoute: typeof InstallTermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-networks': {
      id: '/property-networks'
      path: '/property-networks'
      fullPath: '/property-networks'
      preLoaderRoute: typeof PropertyNetworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-planner': {
      id: '/property-planner'
      path: '/property-planner'
      fullPath: '/property-planner'
      preLoaderRoute: typeof PropertyPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starlink': {
      id: '/starlink'
      path: '/starlink'
      fullPath: '/starlink'
      preLoaderRoute: typeof StarlinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starlink-offer': {
      id: '/starlink-offer'
      path: '/starlink-offer'
      fullPath: '/starlink-offer'
      preLoaderRoute: typeof StarlinkOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vingear': {
      id: '/vingear'
      path: '/vingear'
      fullPath: '/vingear'
      preLoaderRoute: typeof VingearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/business-information': {
      id: '/about/business-information'
      path: '/business-information'
      fullPath: '/about/business-information'
      preLoaderRoute: typeof AboutBusinessInformationRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/capability': {
      id: '/about/capability'
      path: '/capability'
      fullPath: '/about/capability'
      preLoaderRoute: typeof AboutCapabilityRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/how-we-work': {
      id: '/about/how-we-work'
      path: '/how-we-work'
      fullPath: '/about/how-we-work'
      preLoaderRoute: typeof AboutHowWeWorkRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/safety-and-credentials': {
      id: '/about/safety-and-credentials'
      path: '/safety-and-credentials'
      fullPath: '/about/safety-and-credentials'
      preLoaderRoute: typeof AboutSafetyAndCredentialsRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/support': {
      id: '/about/support'
      path: '/support'
      fullPath: '/about/support'
      preLoaderRoute: typeof AboutSupportRouteImport
      parentRoute: typeof AboutRoute
    }
    '/circl-starlink-installations/': {
      id: '/circl-starlink-installations/'
      path: '/'
      fullPath: '/circl-starlink-installations/'
      preLoaderRoute: typeof CirclStarlinkInstallationsIndexRouteImport
      parentRoute: typeof CirclStarlinkInstallationsRoute
    }
    '/circl-starlink-installations/$slug': {
      id: '/circl-starlink-installations/$slug'
      path: '/$slug'
      fullPath: '/circl-starlink-installations/$slug'
      preLoaderRoute: typeof CirclStarlinkInstallationsSlugRouteImport
      parentRoute: typeof CirclStarlinkInstallationsRoute
    }
    '/customer-help/': {
      id: '/customer-help/'
      path: '/'
      fullPath: '/customer-help/'
      preLoaderRoute: typeof CustomerHelpIndexRouteImport
      parentRoute: typeof CustomerHelpRoute
    }
    '/customer-help/$slug': {
      id: '/customer-help/$slug'
      path: '/$slug'
      fullPath: '/customer-help/$slug'
      preLoaderRoute: typeof CustomerHelpSlugRouteImport
      parentRoute: typeof CustomerHelpRoute
    }
    '/event-link/': {
      id: '/event-link/'
      path: '/'
      fullPath: '/event-link/'
      preLoaderRoute: typeof EventLinkIndexRouteImport
      parentRoute: typeof EventLinkRoute
    }
    '/event-link/$slug': {
      id: '/event-link/$slug'
      path: '/$slug'
      fullPath: '/event-link/$slug'
      preLoaderRoute: typeof EventLinkSlugRouteImport
      parentRoute: typeof EventLinkRoute
    }
    '/event-link/organisers': {
      id: '/event-link/organisers'
      path: '/organisers'
      fullPath: '/event-link/organisers'
      preLoaderRoute: typeof EventLinkOrganisersRouteImport
      parentRoute: typeof EventLinkRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-networks/': {
      id: '/property-networks/'
      path: '/'
      fullPath: '/property-networks/'
      preLoaderRoute: typeof PropertyNetworksIndexRouteImport
      parentRoute: typeof PropertyNetworksRoute
    }
    '/property-networks/$slug': {
      id: '/property-networks/$slug'
      path: '/$slug'
      fullPath: '/property-networks/$slug'
      preLoaderRoute: typeof PropertyNetworksSlugRouteImport
      parentRoute: typeof PropertyNetworksRoute
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rural-connections/': {
      id: '/rural-connections/'
      path: '/rural-connections'
      fullPath: '/rural-connections/'
      preLoaderRoute: typeof RuralConnectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rural-connections/$slug': {
      id: '/rural-connections/$slug'
      path: '/rural-connections/$slug'
      fullPath: '/rural-connections/$slug'
      preLoaderRoute: typeof RuralConnectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/': {
      id: '/security/'
      path: '/security'
      fullPath: '/security/'
      preLoaderRoute: typeof SecurityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/$slug': {
      id: '/security/$slug'
      path: '/security/$slug'
      fullPath: '/security/$slug'
      preLoaderRoute: typeof SecuritySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/': {
      id: '/service-areas/'
      path: '/service-areas'
      fullPath: '/service-areas/'
      preLoaderRoute: typeof ServiceAreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/$slug': {
      id: '/service-areas/$slug'
      path: '/service-areas/$slug'
      fullPath: '/service-areas/$slug'
      preLoaderRoute: typeof ServiceAreasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/starlink/': {
      id: '/starlink/'
      path: '/'
      fullPath: '/starlink/'
      preLoaderRoute: typeof StarlinkIndexRouteImport
      parentRoute: typeof StarlinkRoute
    }
    '/starlink/$slug': {
      id: '/starlink/$slug'
      path: '/$slug'
      fullPath: '/starlink/$slug'
      preLoaderRoute: typeof StarlinkSlugRouteImport
      parentRoute: typeof StarlinkRoute
    }
    '/vingear/': {
      id: '/vingear/'
      path: '/'
      fullPath: '/vingear/'
      preLoaderRoute: typeof VingearIndexRouteImport
      parentRoute: typeof VingearRoute
    }
    '/vingear/$slug': {
      id: '/vingear/$slug'
      path: '/$slug'
      fullPath: '/vingear/$slug'
      preLoaderRoute: typeof VingearSlugRouteImport
      parentRoute: typeof VingearRoute
    }
    '/resources/downloads/': {
      id: '/resources/downloads/'
      path: '/resources/downloads'
      fullPath: '/resources/downloads/'
      preLoaderRoute: typeof ResourcesDownloadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/downloads/$slug': {
      id: '/resources/downloads/$slug'
      path: '/resources/downloads/$slug'
      fullPath: '/resources/downloads/$slug'
      preLoaderRoute: typeof ResourcesDownloadsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/packages/$slug': {
      id: '/security/packages/$slug'
      path: '/security/packages/$slug'
      fullPath: '/security/packages/$slug'
      preLoaderRoute: typeof SecurityPackagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/region/$slug': {
      id: '/service-areas/region/$slug'
      path: '/service-areas/region/$slug'
      fullPath: '/service-areas/region/$slug'
      preLoaderRoute: typeof ServiceAreasRegionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AboutRouteChildren {
  AboutBusinessInformationRoute: typeof AboutBusinessInformationRoute
  AboutCapabilityRoute: typeof AboutCapabilityRoute
  AboutHowWeWorkRoute: typeof AboutHowWeWorkRoute
  AboutSafetyAndCredentialsRoute: typeof AboutSafetyAndCredentialsRoute
  AboutSupportRoute: typeof AboutSupportRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutBusinessInformationRoute: AboutBusinessInformationRoute,
  AboutCapabilityRoute: AboutCapabilityRoute,
  AboutHowWeWorkRoute: AboutHowWeWorkRoute,
  AboutSafetyAndCredentialsRoute: AboutSafetyAndCredentialsRoute,
  AboutSupportRoute: AboutSupportRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface CirclStarlinkInstallationsRouteChildren {
  CirclStarlinkInstallationsSlugRoute: typeof CirclStarlinkInstallationsSlugRoute
  CirclStarlinkInstallationsIndexRoute: typeof CirclStarlinkInstallationsIndexRoute
}

const CirclStarlinkInstallationsRouteChildren: CirclStarlinkInstallationsRouteChildren =
  {
    CirclStarlinkInstallationsSlugRoute: CirclStarlinkInstallationsSlugRoute,
    CirclStarlinkInstallationsIndexRoute: CirclStarlinkInstallationsIndexRoute,
  }

const CirclStarlinkInstallationsRouteWithChildren =
  CirclStarlinkInstallationsRoute._addFileChildren(
    CirclStarlinkInstallationsRouteChildren,
  )

interface CustomerHelpRouteChildren {
  CustomerHelpSlugRoute: typeof CustomerHelpSlugRoute
  CustomerHelpIndexRoute: typeof CustomerHelpIndexRoute
}

const CustomerHelpRouteChildren: CustomerHelpRouteChildren = {
  CustomerHelpSlugRoute: CustomerHelpSlugRoute,
  CustomerHelpIndexRoute: CustomerHelpIndexRoute,
}

const CustomerHelpRouteWithChildren = CustomerHelpRoute._addFileChildren(
  CustomerHelpRouteChildren,
)

interface EventLinkRouteChildren {
  EventLinkSlugRoute: typeof EventLinkSlugRoute
  EventLinkOrganisersRoute: typeof EventLinkOrganisersRoute
  EventLinkIndexRoute: typeof EventLinkIndexRoute
}

const EventLinkRouteChildren: EventLinkRouteChildren = {
  EventLinkSlugRoute: EventLinkSlugRoute,
  EventLinkOrganisersRoute: EventLinkOrganisersRoute,
  EventLinkIndexRoute: EventLinkIndexRoute,
}

const EventLinkRouteWithChildren = EventLinkRoute._addFileChildren(
  EventLinkRouteChildren,
)

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface PropertyNetworksRouteChildren {
  PropertyNetworksSlugRoute: typeof PropertyNetworksSlugRoute
  PropertyNetworksIndexRoute: typeof PropertyNetworksIndexRoute
}

const PropertyNetworksRouteChildren: PropertyNetworksRouteChildren = {
  PropertyNetworksSlugRoute: PropertyNetworksSlugRoute,
  PropertyNetworksIndexRoute: PropertyNetworksIndexRoute,
}

const PropertyNetworksRouteWithChildren =
  PropertyNetworksRoute._addFileChildren(PropertyNetworksRouteChildren)

interface SolutionsRouteChildren {
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsSlugRoute: SolutionsSlugRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

interface StarlinkRouteChildren {
  StarlinkSlugRoute: typeof StarlinkSlugRoute
  StarlinkIndexRoute: typeof StarlinkIndexRoute
}

const StarlinkRouteChildren: StarlinkRouteChildren = {
  StarlinkSlugRoute: StarlinkSlugRoute,
  StarlinkIndexRoute: StarlinkIndexRoute,
}

const StarlinkRouteWithChildren = StarlinkRoute._addFileChildren(
  StarlinkRouteChildren,
)

interface VingearRouteChildren {
  VingearSlugRoute: typeof VingearSlugRoute
  VingearIndexRoute: typeof VingearIndexRoute
}

const VingearRouteChildren: VingearRouteChildren = {
  VingearSlugRoute: VingearSlugRoute,
  VingearIndexRoute: VingearIndexRoute,
}

const VingearRouteWithChildren =
  VingearRoute._addFileChildren(VingearRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  CirclStarlinkInstallationsRoute: CirclStarlinkInstallationsRouteWithChildren,
  ContactRoute: ContactRoute,
  CustomerHelpRoute: CustomerHelpRouteWithChildren,
  EstimateRoute: EstimateRoute,
  EventLinkRoute: EventLinkRouteWithChildren,
  InstallTermsAndConditionsRoute: InstallTermsAndConditionsRoute,
  JournalRoute: JournalRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  PropertyNetworksRoute: PropertyNetworksRouteWithChildren,
  PropertyPlannerRoute: PropertyPlannerRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  StarlinkRoute: StarlinkRouteWithChildren,
  StarlinkOfferRoute: StarlinkOfferRoute,
  VingearRoute: VingearRouteWithChildren,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  RuralConnectionsSlugRoute: RuralConnectionsSlugRoute,
  SecuritySlugRoute: SecuritySlugRoute,
  ServiceAreasSlugRoute: ServiceAreasSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  RuralConnectionsIndexRoute: RuralConnectionsIndexRoute,
  SecurityIndexRoute: SecurityIndexRoute,
  ServiceAreasIndexRoute: ServiceAreasIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ResourcesDownloadsSlugRoute: ResourcesDownloadsSlugRoute,
  SecurityPackagesSlugRoute: SecurityPackagesSlugRoute,
  ServiceAreasRegionSlugRoute: ServiceAreasRegionSlugRoute,
  ResourcesDownloadsIndexRoute: ResourcesDownloadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
